#!/bin/bash
set -eu

cd $(dirname $0)

export ANDROID_GOOGLEPLAY_APK_FILE_PATH=$1
export ANDROID_GOOGLEPLAY_TRACK_NAME=$2
echo "Deploying Android for ${ANDROID_GOOGLEPLAY_TRACK_NAME}: ${ANDROID_GOOGLEPLAY_APK_FILE_PATH}"

export ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH="key.p12"

echo $ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_BASE64 | base64 -D > "$ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH"

export SBT_OPTS="-XX:+CMSClassUnloadingEnabled"
sbt run
