#!/bin/bash
set -eu

cd $(dirname $0)

export ANDROID_GOOGLEPLAY_TRACK_NAME=$1
shift

export ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH="key.p12"
echo $ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_BASE64 | base64 -D > "$ANDROID_GOOGLEPLAY_SERVICE_ACCOUNT_KEY_FILE_PATH"

export SBT_OPTS="-XX:+CMSClassUnloadingEnabled"

for apk_file in $@
do
	export ANDROID_GOOGLEPLAY_APK_FILE_PATH=$apk_file
	echo "Deploying Android for ${ANDROID_GOOGLEPLAY_TRACK_NAME}: ${ANDROID_GOOGLEPLAY_APK_FILE_PATH}"
	sbt run
done
